### ISSUE TITLE
Guess The Number Game

### ISSUE THREAD

**Issue by thouravi** [sadanandpai/frontend-mini-challenges#1]
![image](https://user-images.githubusercontent.com/15676184/204078546-5686fcfd-3b4c-4e2e-925d-0ff46c2ca763.png)

I guessed correct number and it said I lost and the number was 89.
I literally guessed the same number.

Maybe you need to look into this. :)

**Comment by sadanandpai** [comment]
Thanks for reporting. Will look into it

**Comment by sadanandpai** [comment]
The issue was for the last successful guess. Fixed along with accessibility. Please verify
