### ISSUE TITLE
Weather App: JS

### ISSUE THREAD

**Issue by sadanandpai** [sadanandpai/frontend-mini-challenges#106]
**Describe the bug**
Icons missing

**Screenshots**
![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/12962887/91a05a3f-96cc-4501-bc5e-6050e6b47d96)

@shruti-sen2004

**Comment by shruti-sen2004** [comment]
Okay..I will look though the matter

**Comment by shruti-sen2004** [comment]
Okay ......so I saw the change that you made in the index.js file........i did that before and it did not work..........thats why I am changing it to the old code that was originally there.
