### ISSUE TITLE
Mad story generator JS 

### ISSUE THREAD

**Issue by hritikbhattacharya** [sadanandpai/frontend-mini-challenges#113]
The Mad Libs project is a fun and interactive program that allows users to create humorous and often nonsensical stories by filling in the blanks with their own words or phrases it is a great way to practice user input, string manipulation, and basic programming concepts while providing an entertaining and creative experience for the users

The project typically involves the following components:
Story Template: Start by creating a story template that includes a narrative with specific placeholders for different parts of speech (e.g., nouns, verbs, adjectives, adverbs).

Requirements:
-Prompt the user to provide words or phrases for each placeholder. Collect and store these user inputs.
-Replace the placeholders in the story template with the user-provided words or phrases, creating a customized and often comical 
  story.
-Present the final generated story to the user, complete with their input, and let them enjoy the humorous results.

Tech stack : 
JS ,html , CSS

Screen shot:
![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/44370586/9334cf35-ead2-4edd-8cb0-52fea7eef71e)
![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/44370586/7d4d4ac6-2a43-460e-9ba9-85bed3491bef)

**Comment by hritikbhattacharya** [comment]
assign to me

**Comment by sadanandpai** [comment]
The repo is now no more under hacktoberfest.
