### ISSUE TITLE
Temperature Converter 

### ISSUE THREAD

**Issue by ARCHITABHATTAD** [sadanandpai/frontend-mini-challenges#128]
**Describe the project you want to add with tech stack**
HTML, CSS, JavaScript

**Expected behavior**
Input the value in either Celsius or Fahrenheit.
Get the converted value without clicking any button.

**Comment by sadanandpai** [comment]
Assigned. Repo is no more a part of Hacktoberfest

**Comment by BrightTNut** [comment]
hi i have already this temp converter project in my repo you , also i proved code also

**Comment by BrightTNut** [comment]
url of my temp converter repo : [https://github.com/BrightTNut/tem-converter]

**Comment by BrightTNut** [comment]
`<!DOCTYPE html>
<html lang="en">
<head>
    
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TEMPERTURE CONVERTER</title>
    <style>
    body{padding: 50px 100px;}
    h1{text-align: center;}
    #container{text-align: center;background-color:rgb(123, 235, 123);padding: 75px;}
    .input{display: inline-block;font-size: 20px;}
    .inp{border: 2px solid grey;padding: 5px 10px;margin: 10px;
    font-size: 30px;width: 250px;text-align: center;border-radius: 10px;display: inline-block;}
    </style>
    
</head>
<body>
    <h1>Tepmerture converture</h1>
    <div id="container">
        <div class="input">
            <label for="">Celsius</label><br>
            <input type="number" value="0" id="cel" class="inp">
        </div>
        <div class="input">
            <label for="">Farenheit</label><br>
            <input type="number" value="32" id="far" class="inp">
        </div>
        <div class="input">
            <label for="">Kelvin</label><br>
            <input type="number" value="-273.15" id="kel" class="inp">
        </div>
    </div>
    <script>
   var cel  = document.getElementById("cel");     
   var far  = document.getElementById("far");
   var kel = document.getElementById("kel");
   cel.addEventListener('input',function(){
let c = this.value;
let f = (c * 9/5) + 32 ;
let k = c-273.15 +273.15+273.15 ;
if(!Number.isInteger(f)){
    f = f.toFixed(4);
}
kel.value=k;
far.value=f;
   })
far.addEventListener('input',function(){
let f = this.value;
let c = (f - 32)* 5/9;
let k = (f - 32) * 5/9 + 273.15 ;
if(!Number.isInteger(c)){
    c = c.toFixed(4);
}
kel.value=k;
cel.value=c;
})

kel.addEventListener('input',function(){
    let k = this.value;
    let c = k - 273.15;
    let f = (k - 273.15) * 9/5 + 32;
    if(!Number.isInteger(k)){
        k = k.toFixed(4);}
    cel.value=c;
    far.value=f;
})
    </script>
</body>
</html>`

**Comment by Kedarnath-Rothe** [comment]
Please assign me this issue
