### ISSUE TITLE
Unit_Converter

### ISSUE THREAD

**Issue by apu52** [sadanandpai/frontend-mini-challenges#130]
**Describe the project you want to add with tech stack**

Hi Sir,
**This is the project where I have made a basic unit converter(feet-inches) with the help of HTML , CSS & JS. Please assign me this issue**
**Expected behavior**

This is the project where I have made a basic unit converter(feet-inches) with the help of HTML , CSS & JS
**Screenshots (optional)**

**Additional context (optional )**

Please Assign Me this issue.

**Comment by apu52** [comment]
@sadanandpai Please assign me this issue.

**Comment by sadanandpai** [comment]
@apu52 
Assigned. Repo is no more a part of Hacktoberfest

**Comment by apu52** [comment]
Ok
