### ISSUE TITLE
Frontend Notebook

### ISSUE THREAD

**Issue by apu52** [sadanandpai/frontend-mini-challenges#131]
**Describe the project you want to add with tech stack**

**In this frontend project I have made a simple landing page of a online notebook where we save our daily work in the form of blogs.....**
**Expected behavior**

The notebook is made with HTML, CSS, JS & react.
**Screenshots (optional)**

**Additional context (optional )**

Please assign me this issue.

**Comment by apu52** [comment]
@sadanandpai Please assign me this issue.

**Comment by arpansaha13** [comment]
This repository is meant for front-end challenges and not full-blown websites/UIs.
I am closing this issue as invalid.
