### ISSUE TITLE
car racing game

### ISSUE THREAD

**Issue by darshan45672** [sadanandpai/frontend-mini-challenges#135]
**Describe the project you want to add with tech stack**
I have developed a car racing game using html, CSS and javascript.

**Expected behavior**

 I would like upgrade the project. please assign me this issue.
**Screenshots (optional)**

![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/109609462/03daf793-17b8-4cb7-b7b0-47e4f0553df5)
![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/109609462/4a14912f-d9f0-49c4-bd0b-f66d0baace3c)
![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/109609462/f217cdaf-b222-450b-be3b-3fb7ba00d0ce)

**Additional context (optional )**
I want to contribute so please assign me the issue

**Comment by KarthikGanapaR** [comment]
I would like to work on this project

**Comment by darshan45672** [comment]
fuck offf

**Comment by sadanandpai** [comment]
Repo is no more a part of Hacktoberfest

**Comment by darshan45672** [comment]
Ok thank you
