### ISSUE TITLE
Add a Music Kit App

### ISSUE THREAD

**Issue by shivam200446** [sadanandpai/frontend-mini-challenges#137]
**Describe the project you want to add with tech stack**

Creating a music kit app feature using JavaScript involves building a web application that allows users to interact with and manipulate music. Also operated by Keyboard
**Expected behavior**

**Screenshots (optional)**

![eee](https://github.com/sadanandpai/frontend-mini-challenges/assets/127589548/47c1ed5a-00c0-4e36-8497-a36986364d92)
tional )**
**Additional context (op

**Comment by shivam200446** [comment]
i want to work on it! assign me

**Comment by sadanandpai** [comment]
Repo is no more a part of Hacktoberfest

**Comment by shivam200446** [comment]
@sadanandpai  No worry Bhaiya I will still work on it.
