### ISSUE TITLE
Add a Dice game 

### ISSUE THREAD

**Issue by shivam200446** [sadanandpai/frontend-mini-challenges#138]
**Describe the project you want to add with tech stack**

It will update the displayed number to simulate rolling a dice. You can further enhance this example by adding animations and other features to make it more interactive.
**Expected behavior**

**Screenshots (optional)**

![dice](https://github.com/sadanandpai/frontend-mini-challenges/assets/127589548/7eec80bc-b39b-4826-b271-11d2e7d5ec4a)

**Additional context (optional )**

**Comment by shivam200446** [comment]
@sadanandpai Hey!, I want to work on it. Assign me

**Comment by AckermanLevi1** [comment]
@shivam200446 I would love to contribute in it

**Comment by sadanandpai** [comment]
Repo is no more a part of Hacktoberfest
