### ISSUE TITLE
Add a Digital Clock

### ISSUE THREAD

**Issue by shivam200446** [sadanandpai/frontend-mini-challenges#139]
**Describe the project you want to add with tech stack**

Creating a simple digital clock feature using JavaScript. we can further use the design and functionality to match your specific requirements.
**Expected behavior**

**Screenshots (optional)**

![clock](https://github.com/sadanandpai/frontend-mini-challenges/assets/127589548/35803836-8d72-4492-9f69-4ef2f6add944)

**Additional context (optional )**

**Comment by shivam200446** [comment]
@sadanandpai assign me! I want to work further on it.

**Comment by sadanandpai** [comment]
Repo is no more a part of Hacktoberfest

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me
