### ISSUE TITLE
chrome dinosours game

### ISSUE THREAD

**Issue by Kalivarapubindusree** [sadanandpai/frontend-mini-challenges#156]
**Describe the project you want to add with tech stack**
chrome dinosours game

**Expected behavior**
I want to create chrome dinosours game which is monitoring with keyboard

**Screenshots (optional)**
![WhatsApp Image 2023-10-09 at 9 15 16 PM](https://github.com/sadanandpai/frontend-mini-challenges/assets/114821855/d698dbe0-0a8e-4a3a-b0a5-49781ffbf4bc)

**Additional context (optional )**
languages used html,css,javascript.

**Comment by Kalivarapubindusree** [comment]
Is this repo not part of hacktoberfest or hacksquad??

**Comment by DevanshKyada27** [comment]
Hey @sadanandpai can you assign me this issue want to work on it.
