### ISSUE TITLE
Add a BMI calculator

### ISSUE THREAD

**Issue by Arnabhit** [sadanandpai/frontend-mini-challenges#159]
**Describe the project you want to add with tech stack**
Hey there @sadanandpai i want to add a BMI calculator here which will calculate the Body Mass Index. The tech stack is html,css, javascript

**Expected behavior**
This BMI Calculator is for all the fitness freaks out there. The BMI Calculator takes your height and weight as input and gives BMI (Body Mass Index) as an output.

**Comment by Tushar2930** [comment]
@sadanandpai  @Arnabhit can I work on this?

**Comment by Arnabhit** [comment]
@sadanandpai  why you have removed the hacktober fest label😅

**Comment by Kedarnath-Rothe** [comment]
Please assign me this issue

**Comment by arpansaha13** [comment]
@Kedarnath-Rothe would you like to take it up?

**Comment by Kedarnath-Rothe** [comment]
Please label this issue as hactoberfest

**Comment by arpansaha13** [comment]
This repository is not part of hacktoberfest

**Comment by DevanshKyada27** [comment]
Hey @sadanandpai @arpansaha13 can you please assign me this issue want to work on it.

**Comment by itsayopapi** [comment]
@sadanandpai Can you please assign this issue to me

**Comment by itsayopapi** [comment]
@arpansaha13 Please have a look at my PR
