### ISSUE TITLE
[React/todo-list]: Todo-items not being persisted across reloads

### ISSUE THREAD

**Issue by harshalhonde21** [sadanandpai/frontend-mini-challenges#185]
When you add a TODO in the TODO application, it gets added successfully. However, the application's creator may not have considered why users add TODOs in the first place - to serve as reminders. Unfortunately, as it stands, these TODOs disappear when you reopen or refresh the application. To ensure a better user experience, it's crucial to implement a feature that stores these TODOs in local storage, allowing them to persist indefinitely until the user manually deletes them.

adding image
![ref](https://github.com/sadanandpai/frontend-mini-challenges/assets/105191619/f7e4d2d4-ba7f-48c8-84f3-ebe64797d8a5)

after refreshing the todo delete/disappers
![refs](https://github.com/sadanandpai/frontend-mini-challenges/assets/105191619/b0b6a727-29f2-48d8-8856-4399ca1c3628)

**Comment by harshalhonde21** [comment]
Please assign this issue to me i will add the awesome nice feature in it

**Comment by proghax333** [comment]
I've fixed this issue in my pull request.
