### ISSUE TITLE
Add Finance Tracker Website

### ISSUE THREAD

**Issue by sujitmahapatra** [sadanandpai/frontend-mini-challenges#186]
**Describe the project you want to add with tech stack**
I would like to propose adding a new project to the repository. The project is called "Finance Tracker Website." This web application allows users to manage their personal finances by tracking income and expenses. It includes features such as transaction management, categorization, transaction history, and a visually appealing user interface.

**Tech Stack:**
- Frontend: HTML, CSS, JavaScript
- Backend: Not applicable (front-end only)
- Libraries: None (vanilla JavaScript)
- Frameworks: None
- Database: None (data stored locally)
- Hosting: Not applicable (static website)

**Expected behavior**
I expect that this project proposal will be reviewed and, if approved, added to the repository as a new challenge. The challenge should include the project description, tech stack details, and any relevant information to help contributors understand and work on the project.

**Screenshots (optional)**
https://github.com/sujitmahapatra/frontend-mini-challenges/blob/0a36075c73786b8f1ebd360c11938ca416bf70a7/native/machine-coding/Finance%20Tracker/Finance%20Tracker.png

**Additional context (optional)**
This project is designed to help individuals manage their personal finances more effectively. It can serve as a useful tool for learning and practicing web development skills, especially in the areas of HTML, CSS, and JavaScript. It's intended to be a beginner-friendly challenge that contributors can use to enhance their web development skills.

**Comment by sujitmahapatra** [comment]
Hi @sadanandpai,

Thank you for assigning issue #186 to me. I've already reviewed the
existing pull request, and it appears to be correct from my side. If there
are any specific steps or further actions needed, please let me know, and
I'll be happy to proceed accordingly.

Best regards, sujitmahapatra

**Comment by sadanandpai** [comment]
Please check the comments
