### ISSUE TITLE
Memory Game to JS Mini Project

### ISSUE THREAD

**Issue by Paulie-Aditya** [sadanandpai/frontend-mini-challenges#195]
**Describe the project you want to add with tech stack**
HTML, Javascript

can be seen here: 
https://github.com/Paulie-Aditya/js-games/tree/main/memory-game

**Comment by Paulie-Aditya** [comment]
Please do assign this to me if it interests you

**Comment by sadanandpai** [comment]
is it same as this?

If yes, maintain the high quality standards while implementation
