### ISSUE TITLE
update LICENSE section in README

### ISSUE THREAD

**Issue by malivinayak** [sadanandpai/frontend-mini-challenges#196]
**Is your feature request related to a problem? Please describe.**
Updated the LICENSE section in the README file **to enhance the presentation.**

**Describe the solution you'd like**
Added a MIT logo, license badge and replaced the previous text with a cleaner format, including a hyperlink to the LICENSE file.

**Additional context**

- Current:
> ![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/66154908/29fefb3f-a8ba-49e8-8aa7-ad05c423b794)
- Updated:
> ![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/66154908/103aa4cf-d20a-487d-b51a-5efc18515072)

**Comment by arpansaha13** [comment]
This logo is of MIT institute and not of MIT License.
Also this change is **not** required.
