### ISSUE TITLE
[React] Progress-bar challenge is not responsive

### ISSUE THREAD

**Issue by VinayKokate22** [sadanandpai/frontend-mini-challenges#199]
**Describe the bug**
Progressbar a react-mini project is not responsive

**Expected behavior**
Suppose to be responsive for all devices

**Screenshots**
![12 10 2023_10 04 28_REC](https://github.com/sadanandpai/frontend-mini-challenges/assets/114766745/74d69e42-225c-43c4-9ff9-bcfe8f6ee014)

**Additional context**

**Comment by VinayKokate22** [comment]
@sadanandpai i would like to work on it, can you assign me the issue

**Comment by srujanmelam** [comment]
Hey hi is this issue resolved ? if not i would like to contribute

**Comment by arpansaha13** [comment]
Yes u can open a PR for it anytime

**Comment by srujanmelam** [comment]
Yeah Sure Thanks

**Comment by srujanmelam** [comment]
can you specify the file where the progress bar logic is present?

**Comment by arpansaha13** [comment]
This is the [react app]()

You can find the challenges in `src/` folder

**Comment by srujanmelam** [comment]
<img width="548" alt="progressbar" src="https://github.com/sadanandpai/frontend-mini-challenges/assets/61271544/4b73932f-9381-440d-a566-43aa2115cd26">
is it ok please let me know if any necessary changes needed !?

**Comment by arpansaha13** [comment]
Looks good to me!

**Comment by srujanmelam** [comment]
cool ill raise the pr. is there any specific branch naming should i have to follow..?

**Comment by arpansaha13** [comment]
No its fine u can open the PR targetting the main branch

**Comment by srujanmelam** [comment]
i raised pr please look into it and let me know if any changes are needed thanks
