### ISSUE TITLE
AI Image Generator 

### ISSUE THREAD

**Issue by AaadityaG** [sadanandpai/frontend-mini-challenges#200]
**Describe the project you want to add with tech stack**
HTML / CSS / JS

**Expected behavior**
Generating images with prompt

**Screenshots (optional)**
![AI Image Generator - 2](https://github.com/sadanandpai/frontend-mini-challenges/assets/114663382/79160eb4-6115-4ef8-a1f1-8f51f790e37d)

**Additional context (optional )**
Checkout at - https://ai-images-generator-three.vercel.app/

**Comment by arpansaha13** [comment]
This repo is specifically for frontend challenges. Anything related to AI is not required.
