### ISSUE TITLE
Favicon is looking bad

### ISSUE THREAD

**Issue by bilalmirza74** [sadanandpai/frontend-mini-challenges#204]
**Describe the bug**
Favicon is looking bad let me do enhance 

**Expected behavior**
favicon background will be get transparent 

**Screenshots**

![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/84387676/92ec6aad-d90a-444a-a32b-d3ff23f34f43)

**Additional context**

**Comment by arpansaha13** [comment]
This change is not required for now
