### ISSUE TITLE
Movie-Info-App

### ISSUE THREAD

**Issue by AckermanLevi1** [sadanandpai/frontend-mini-challenges#215]
**Add a movie information giving website using HTML, CSS, Javascript, that give all relevant information of any movie input by the user**

**Expected behavior**
on clicking button- cast, imdb rating, poster, director like information should be displayed

**Screenshots (optional)**

**Additional context (optional )**

**Comment by AckermanLevi1** [comment]
@sadanandpai pls assign this issue to me

**Comment by arpansaha13** [comment]
This repository is specifically for logical front-end challenges and not for full-blown websites/UIs.
So this issue will not be worked on.

**Comment by AckermanLevi1** [comment]
Hey @arpansaha13 I guess it is not a full blown website as we are only making a API call in it. It is similar to other projects which are already merged. Please reconsider it.

**Comment by sadanandpai** [comment]
HTML + CSS full pages will be the future plan, If it is an API fetching and displaying piece, will consider it.
