### ISSUE TITLE
Broken Logo and name for Finance tracker

### ISSUE THREAD

**Issue by VinayakGaikwad101** [sadanandpai/frontend-mini-challenges#216]
**Describe the bug**
Logo for Finance Tracker does not display

**Expected behavior**
It should display the logo properly, along with the name

**Screenshots**
![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/93867583/2db42cc1-39e3-4c36-aca8-071b8ca4fbf8)

**Comment by VinayakGaikwad101** [comment]
Hello Sir, please allow me to work on this issue :)

**Comment by sadanandpai** [comment]
please address for **Currency Converter** too

The right developer can be found from closed PRs list

**Comment by debajoti** [comment]
is it still open?
