### ISSUE TITLE
Text Ananlyzer

### ISSUE THREAD

**Issue by JiyaGupta-cs** [sadanandpai/frontend-mini-challenges#221]
# TextTrove - A Text Analyzer :pencil2: #
## About The Project ##

TextTrove is a versatile text processing and analysis tool designed to make working with text easier and more efficient. Whether you're a content creator, a student, or a data scientist, this tool provides a range of essential features to help you understand, manipulate, and extract meaningful insights from text.

## Features - ##
:abcd: **Lowercase Conversion:** This feature converts all the text to lowercase. It's useful for standardizing text and making it consistent, especially for text mining and analysis.

:capital_abcd: **Uppercase Conversion:** Similar to lowercase conversion, this feature converts text to uppercase. It can also be valuable for standardization and emphasis.

 🔊: **Text-to-Speech:** This feature allows users to input text and have it read aloud using a text-to-speech engine. It can be beneficial for accessibility and enhancing the user experience.

8️⃣ **Word Count**: This feature calculates the number of words in the text. It typically considers spaces and punctuation to identify word boundaries.

9️⃣ **Character Count:** This feature counts the total number of characters in the text, including spaces and punctuation.

:alarm_clock: **Time to Read:** Estimate the time it would take for an average reader to read the text at a standard reading pace. This can be presented in minutes or minutes and seconds.

## Built With - ##
  * React JS :atom_symbol:
  * Bootstrap

**Comment by arpansaha13** [comment]
Third-party libraries like Bootstrap are not allowed actually. Everything needs to be implemented manually.

**Comment by arpansaha13** [comment]
I am closing this issue due to invalid solution #222.
Please comment here if you can write a valid solution. In that case, we will reopen the issue and PR.
