### ISSUE TITLE
Want to create react todo project dynamic project which is different from other todo 

### ISSUE THREAD

**Issue by harshalhonde21** [sadanandpai/frontend-mini-challenges#228]
All the todo are disapper after the adding and refreshing we should add localstorage to do the project dyanamic

**Comment by harshalhonde21** [comment]
assign this issue to me

**Comment by arpansaha13** [comment]
Duplicate of issue #185 

You are already assigned in that issue.

**Comment by arpansaha13** [comment]
You may open a PR to add this change

**Comment by arpansaha13** [comment]
@harshalhonde21 I am closing this issue since it is a duplicate of another.
You can consider #185 as the issue for your PR
