### ISSUE TITLE
Add Typing Speed Test Application

### ISSUE THREAD

**Issue by psykat1116** [sadanandpai/frontend-mini-challenges#230]
**Describe the project you want to add with tech stack**
Want to add a typing speed testing website. Where user can find their typing speed per minutes. Tech stack used **HTML**, **CSS**, **Javascript**

**Expected behavior**
There will be a timer for 60s. As soon as you start typing timer will start. Between the time depending on how fast and correctly you type your score will be given. The typing text will be shuffling every time you restart.

**Screenshots (optional)**
![Capture2](https://github.com/sadanandpai/frontend-mini-challenges/assets/95569573/e2585a23-3d38-4eb1-a018-d0958b37d5fe)

**Comment by arpansaha13** [comment]
It is already implemented in vanilla JS. If you identify any bugs or want to add a feature in it then you can open a PR. Remember to mention your intended change in this issue. Or you may do this in React or Vue.

https://sadanandpai.github.io/frontend-mini-challenges/native/machine-coding/typing-speed-test/

**Comment by psykat1116** [comment]
Ok then i will do this in React JS. Please assign me for this under **Hacktoberfest**.

**Comment by arpansaha13** [comment]
Repo is not part of hacktoberfest
