### ISSUE TITLE
Speed Typing Game

### ISSUE THREAD

**Issue by Vivek-GuptaXCode** [sadanandpai/frontend-mini-challenges#231]
This project/challenge is a typing test game that shows the accuracy,time taken and the words per minute of the user.

![Screenshot from 2023-10-14 16-35-39](https://github.com/sadanandpai/frontend-mini-challenges/assets/145761266/92bac516-ff41-4c28-ba70-3e6812935e43)

![Screenshot from 2023-10-14 16-35-26](https://github.com/sadanandpai/frontend-mini-challenges/assets/145761266/5f9cc458-ae37-4159-8de6-0b70ac284689)

![Screenshot from 2023-10-14 16-39-41](https://github.com/sadanandpai/frontend-mini-challenges/assets/145761266/8549e690-e3ca-4356-a5a4-51a593a69b9d)

I hope you would allow me to work on this issue.

**Comment by arpansaha13** [comment]
It is already implemented in vanilla JS. If you identify any bugs or want to add a feature in it then you can open a PR. Remember to mention your intended change in this issue. Or you may do this in React or Vue.

https://sadanandpai.github.io/frontend-mini-challenges/native/machine-coding/typing-speed-test/

**Comment by Vivek-GuptaXCode** [comment]
okay thanks for pointing out
