### ISSUE TITLE
Bill split CSS issue (native JS)

### ISSUE THREAD

**Issue by arpansaha13** [sadanandpai/frontend-mini-challenges#235]
**Describe the bug**
CSS issue with navbar in "Bill split" challenge

**Expected behavior**
The navbar should look proper like in the other challenges

**Screenshots**
![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/82361490/3539738c-3797-463e-ac76-67b129cda600)

**Possible reason**
Conflicts with core CSS

**Comment by kumarvivekpandey** [comment]
@arpansaha13 hey Arpanaha could you please assign this to me

**Comment by kumarvivekpandey** [comment]
issue resolved you can check and merge it 
https://deploy-preview-241--preeminent-tapioca-4294b2.netlify.app/machine-coding/bill-spilt/
![Screenshot (76)](https://github.com/sadanandpai/frontend-mini-challenges/assets/35356580/114a7a20-7e6d-4f08-8b26-896518c1625d)

**Comment by arpansaha13** [comment]
Thanks a lot for fixing the issue
A maintainer will review and merge soon within today
