### ISSUE TITLE
403: when try to push in some chnages in my branch

### ISSUE THREAD

**Issue by kumaratul60** [sadanandpai/frontend-mini-challenges#25]
getting error:
`remote: Permission to sadanandpai/frontend-mini-challenges.git denied to kumaratul60.
fatal: unable to access 'https://github.com/sadanandpai/frontend-mini-challenges.git/': The requested URL returned error: 403`

steps I follow:

- git clone <branch>
- git checkout -b my-branch
- add some challenges in my branch
- git status
- git add .
- git commit -m "added challenge"
- git push origin my-branch

getting error when try to push code in my branch

**Comment by sadanandpai** [comment]
Please fork the repo and then follow the above steps
