### ISSUE TITLE
[JS] typing-speed-test : Sentence to be typed is aligned to right side of the screen

### ISSUE THREAD

**Issue by Vivek-GuptaXCode** [sadanandpai/frontend-mini-challenges#254]
### Framework/code-stack

Native (HTML, CSS, and JS)

### Scope

typing-speed-test

### Description

the sentence to be typed that is being displayed on the right side of the screen.

![Screenshot from 2023-10-16 17-54-01](https://github.com/sadanandpai/frontend-mini-challenges/assets/145761266/cbb67aa7-94dc-4bfd-ab1b-79cd941d1e03)

### Expected behaviour

It should be in the center of the screen.

### Suggested Solutions

some css needs to be fixed.Please allow me to contribute.

**Comment by Vivek-GuptaXCode** [comment]
I would like on work on this issue.

**Comment by sadanandpai** [comment]
This is intentional as the letters will be easy to in the center of the screen than at the left

**Comment by Vivek-GuptaXCode** [comment]
upto u ,but it is my opinion that it doesnt suits the UI
