### ISSUE TITLE
Weather App using HTML, CSS & JS

### ISSUE THREAD

**Issue by Iron-Thunder** [sadanandpai/frontend-mini-challenges#262]
want to add a responsive weather app using HTML, CSS and JS with some basic and interesting features.

**Comment by Iron-Thunder** [comment]
Please assign this issue to me under hacktoberfest 2k23

**Comment by arpansaha13** [comment]
If you could provide a screenshot it would be good
And this repo is not part of hacktoberfest

**Comment by sadanandpai** [comment]
We already have a weather app

https://sadanandpai.github.io/frontend-mini-challenges/native/machine-coding/weather-app/
