### ISSUE TITLE
E-Commerce Website

### ISSUE THREAD

**Issue by itztani** [sadanandpai/frontend-mini-challenges#263]
**Describe the project you want to add with tech stack**

This website is fully responsive. it uses html, css and js.  

**Screenshots (optional)**

![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/147174096/7a9f051d-0210-4e89-a5a1-3a81346a40ab)

![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/147174096/239eba9e-7651-4af0-8e37-4febe4e4c78c)

![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/147174096/c4e9b0fd-91d4-4a1b-a89b-3440de6a11fc)

Please allow me to do this project

**Comment by arpansaha13** [comment]
Full websites/UIs are not planned in this repositiry yet
