### ISSUE TITLE
[New]: QR code generator

### ISSUE THREAD

**Issue by itztani** [sadanandpai/frontend-mini-challenges#266]
### Framework/code-stack

Native (HTML, CSS, and JS)

### Description

To Generate QR Code

### Similar challenges

no

**Comment by itztani** [comment]
Image Search Engine

**Comment by sadanandpai** [comment]
can you put a screenshot if you have

**Comment by itztani** [comment]
![Uploading IMG-20231020-WA0017.jpg…]()

**Comment by itztani** [comment]
![IMG-20231020-WA0015(1)](https://github.com/sadanandpai/frontend-mini-challenges/assets/147174096/248c1c7d-ca35-42f1-9fba-f0e58c464b0b)
![IMG-20231020-WA0016](https://github.com/sadanandpai/frontend-mini-challenges/assets/147174096/95b5faeb-3efd-494b-b8ec-9978caa2496f)

**Comment by itztani** [comment]
![IMG-20231020-WA0015(1)](https://github.com/sadanandpai/frontend-mini-challenges/assets/147174096/2ebc0208-87f2-4046-a0d0-d39e65a12a8c)
![IMG-20231020-WA0016](https://github.com/sadanandpai/frontend-mini-challenges/assets/147174096/0782ab30-071d-46c3-ae99-74b98e60509a)
![IMG-20231020-WA0017](https://github.com/sadanandpai/frontend-mini-challenges/assets/147174096/b94f3feb-6196-4fce-813b-1f93f2b1b80d)
