### ISSUE TITLE
Project : Want to add SpotifyApp 

### ISSUE THREAD

**Issue by HIMANSHU00KUMAR** [sadanandpai/frontend-mini-challenges#268]
### Framework/code-stack

Native (HTML, CSS, and JS)

### Description

Want to add a spotify app..
please assign me this issue..

### Similar challenges

NO

### Screenshots

![spotifyss](https://github.com/sadanandpai/frontend-mini-challenges/assets/114851863/c121798f-6377-402f-9b08-edf8469b4a55)

**Comment by sadanandpai** [comment]
This repo is not for full E2E projects. A standard music player implementation is right fit
