### ISSUE TITLE
[Feature_Request] Quiz App With Timer

### ISSUE THREAD

**Issue by Vivek-GuptaXCode** [sadanandpai/frontend-mini-challenges#270]
Problem : Limited number of questions and all are same.

Solution : Adding more questions in questions.json file and few changes in js file can cause the app to select a random group of questions from the pool of questions in the json file each time the page is refreshed or a restart is triggered.This would make it more challenging.

I request you to allow me to work on this issue.

**Comment by arpansaha13** [comment]
You can add more questions. But the number of questions on display should be limited so that the quiz can be ended very quickly, i.e like 5 to 8 questions on display at a time

Also make sure to write comments saying that "this part of the code is for randomizing the questions"

**Comment by arpansaha13** [comment]
If you face any problem with your PR then you can tag me

**Comment by Vivek-GuptaXCode** [comment]
Thanks for the assignment and i figured out the mistake i was doing previously and will make sure to implement all the suggestions

**Comment by Vivek-GuptaXCode** [comment]
Thank you for merging the PR.
