### ISSUE TITLE
Word-Counter

### ISSUE THREAD

**Issue by AckermanLevi1** [sadanandpai/frontend-mini-challenges#271]
### Framework/code-stack

Native (HTML, CSS, and JS)

### Description

<h4>It will take words as input from the user and then count number of paragraphs, words, characters, sentences written by user</h4>

### Similar challenges

No

### Screenshots

![Screenshot (79)](https://github.com/sadanandpai/frontend-mini-challenges/assets/114604529/8c61e99b-08ce-444b-82dd-5ba63e5c6617)

**Comment by AckermanLevi1** [comment]
Pls assign me this issue @sadanandpai

**Comment by manavb2214** [comment]
Hey @sadanandpai !!! I am already working on this issue !!! Could you please assign it to me ??

**Comment by arpansaha13** [comment]
Background is not needed. You can remove background

**Comment by manavb2214** [comment]
I have already done the same @arpansaha13 !!! You can check for the same !!!

**Comment by arpansaha13** [comment]
Check your PR once @manavb2214
