### ISSUE TITLE
[New]: tic tac toe project with neon theme

### ISSUE THREAD

**Issue by Ganesh2904** [sadanandpai/frontend-mini-challenges#277]
### Framework/code-stack

Native (HTML, CSS, and JS)

### Description

This is a Tic Tac Toe javascript game made using html css and js. it has neon theme. and it also shows the scores of two players.

### Similar challenges

Yes, 
but the available  project has minimal theme but this project has neon theme. 
And this project also shows the scores of two players.

**Comment by arpansaha13** [comment]
Tic tac toe is already there in native js

https://sadanandpai.github.io/frontend-mini-challenges/native/machine-coding/tic-tac-toe/

A different theme won't make it a new challenge

**Comment by arpansaha13** [comment]
If you want to show scores of two players then add this feature in the existing project
