### ISSUE TITLE
[New]: Want to Add Marketplace UI Page 

### ISSUE THREAD

**Issue by Adidem23** [sadanandpai/frontend-mini-challenges#284]
### Framework/code-stack

React

### Description

I want to add  NFT marketplace UI frotnend which has features of typical NFT marketplace 

### Similar challenges

All other Challenges are realted to the tradtional Web2 related projects . This challenge is related mostly to the web3 stack so 

### Screenshots

<img width="960" alt="Screenshot 2023-10-23 121240" src="https://github.com/sadanandpai/frontend-mini-challenges/assets/124609794/c1036686-7b50-4907-b655-4ef559478441">

<img width="958" alt="Screenshot 2023-10-23 121258" src="https://github.com/sadanandpai/frontend-mini-challenges/assets/124609794/d62f86f1-076b-449f-9644-7a31340aac58">

<img width="960" alt="Screenshot 2023-10-23 121338" src="https://github.com/sadanandpai/frontend-mini-challenges/assets/124609794/80d5be15-b945-4b03-8e52-19cffe9a56c9">

**Comment by sadanandpai** [comment]
FMC is only for mini-challenges and not for full end-to-end websites as of now.

**Comment by Adidem23** [comment]
Ok I Will try to add another mini challenge is it fine then ??
