### ISSUE TITLE
Dockerize the app

### ISSUE THREAD

**Issue by Adidem23** [sadanandpai/frontend-mini-challenges#298]
I want to add docker image for the react app

**Comment by sadanandpai** [comment]
The codebase is revamped. Dockerization is helpful.

**Comment by Adidem23** [comment]
Please Assign it to me I will try to do it

**Comment by arpansaha13** [comment]
You can open a PR for it whenever you are comfortable 👍

**Comment by sadakchap** [comment]
@sadanandpai Is this issue available? Would you assign it to me?

**Comment by SachinMS4** [comment]
@sadanandpai 
I have recently worked on similar feature, I am up for this if this is open to work.

**Comment by Gamoneon** [comment]
@sadanandpai please assign this to me. Thank you
