### ISSUE TITLE
[New]: Add Drum set for JS

### ISSUE THREAD

**Issue by Asymtode712** [sadanandpai/frontend-mini-challenges#308]
### Framework/code-stack

Native (HTML, CSS, and JS)

### Description

A cool drum set app made using HTML, CSS & JS.
It can be played through both options - keys and on-click.

### Similar challenges

No

### Screenshots

![drum-set](https://github.com/sadanandpai/frontend-mini-challenges/assets/115717746/042862a0-1c1f-418e-99cf-1c8598f8051e)

**Comment by arpansaha13** [comment]
How are you saying there are no similar challenges?

This exact challenge already exists in this repo
https://sadanandpai.github.io/frontend-mini-challenges/native/machine-coding/music-kit/
