### ISSUE TITLE
React: OTP: Allows invalid characters

### ISSUE THREAD

**Issue by sadanandpai** [sadanandpai/frontend-mini-challenges#321]
### Framework/code-stack

React

### Scope

OTP

### Description

<img width="435" alt="image" src="https://github.com/sadanandpai/frontend-mini-challenges/assets/12962887/4b8d2533-4834-4d54-9641-dd895d4a21fd">

### Expected behaviour

The text e should not be allowed and also should not allow more than 1 digit in any of the field.

**Comment by lopster568** [comment]
Hi, I've understood the issue and I can think of a fix for it. Please assign the issue to me.🚀🚀🚀

**Comment by vtkmy** [comment]
Hello, I'm very interested in your problem. Can you assign it to me?

**Comment by sadanandpai** [comment]
@vtkmy @lopster568 this is got fixed by @JeevaRamanathan. Please pick any other issue

**Comment by sadanandpai** [comment]
https://github.com/sadanandpai/frontend-mini-challenges/issues/199
Check this out
