### ISSUE TITLE
current changes are not reflecting

### ISSUE THREAD

**Issue by kumaratul60** [sadanandpai/frontend-mini-challenges#35]
@sadanandpai, every time when we want to add some challenges so we fork first then clone, npm i, etc steps follow?

I want to add some challenges, but before creating a new branch from the previously created main branch, run git pull, but there are no changes that are added showing: Already up to date.
so how to updated with the latest code?

also plz update the following:

react>src>helpers:

in contributer.ts:
`['kumaratul60', { name: 'Atul Kumar Awasthi', pic: 'https://avatars.githubusercontent.com/u/53579888?v=4' }],`

in challenges.ts:
```
[
    'stack',
    {
      title: 'Stack',
      link: 'stack',
      difficulty: 'easy',
      developer: 'kumaratul60',
      tags: [],
      isNew: true,
    },
  ],
```

**Comment by sadanandpai** [comment]
@kumaratul60 done

**Comment by sadanandpai** [comment]
UI is broken on mobile

<img width="398" alt="image" src="https://github.com/sadanandpai/frontend-mini-challenges/assets/12962887/d0241d79-ec67-47ee-a6d2-be40d6a5d859">

Also stack is accepting more than its length 5

**Comment by kumaratul60** [comment]
fix it soon,

and what about, if i want to add more challenges so by running  git pull current changes are not going to reflect in my main branch,
this main branch is created when I fork the project the first time,  @sadanandpai

**Comment by sadanandpai** [comment]
https://stackoverflow.com/questions/7244321/how-do-i-update-or-sync-a-forked-repository-on-github
