### ISSUE TITLE
[Vue]: Add solution for stack

### ISSUE THREAD

**Issue by jaydadhaniya** [sadanandpai/frontend-mini-challenges#351]
### Framework/code-stack

Vue

### Description

I want to create a stack data structure mini-challenge in VueJs, allowing users to perform certain actions like push, pop, peek, isStackEmpty, isStackPop.

The tech stack is VueJS

### Similar challenges

No

**Comment by arpansaha13** [comment]
By the way, if the challenge is already there in the list then you can directly open the PR without opening an issue

**Comment by jaydadhaniya** [comment]
Oh, Okay. 
I will keep in mind
