### ISSUE TITLE
[New]: Add Anagram Checker

### ISSUE THREAD

**Issue by Manmit124** [sadanandpai/frontend-mini-challenges#363]
### Framework/code-stack

React

### Description

Create a web application where users can input two words or phrases, and the application will determine whether they are anagrams or not. An anagram is a word or phrase formed by rearranging the letters of another. The application should provide instant feedback and visually indicate whether the input is an anagram or not.

### Similar challenges

No

**Comment by arpansaha13** [comment]
You can open a PR for it anytime 👍

**Comment by Manmit124** [comment]
ok
