### ISSUE TITLE
Adding the Search, Pagination Functionality to the Individual Challenges section

### ISSUE THREAD

**Issue by 721-atikshaikh** [sadanandpai/frontend-mini-challenges#376]
### Framework/code-stack

Native (HTML, CSS, and JS)

### Scope

Core Application

### Description

1. **Search Functionality:** Implement a search bar to allow users to quickly find challenges by name. This should support partial matches and be case-insensitive to ensure ease of use.
2. **Pagination Functionality:** Instead of loading all challenges simultaneously, introduce pagination. This will reduce initial load times, improve performance, and allow users to navigate through challenges in a more organized manner.
3. **Sorting Functionality:** Provide users with the ability to sort challenges by name, difficulty, and newly added. Sorting should be both ascending and descending to cater to various user preferences.

### Screenshots

I am open to discussion as per the requirements @sadanandpai !

**Comment by sadanandpai** [comment]
@721-atikshaikh Search, pagination & sort are great features to go ahead with. I suggest to pick one at a time. Also are you planning to implement the search for all tech or as a web components shared

**Comment by 721-atikshaikh** [comment]
Hi @sadanandpai , sorry for the delay just dealing a lot in life. Will come back with a proper plan on how to proceed with a single feature. BTW do we have any community channel anywhere on Slack/Discord or any other place ? It would be easily available to chat

**Comment by sadanandpai** [comment]
https://t.me/+rc6Rwd77G_gzMjA1 @721-atikshaikh

**Comment by 721-atikshaikh** [comment]
@sadanandpai Joined the group. Also I see this issue has been segregated into various small issues. Great idea ! Will pick one of them and start working on it.

**Comment by sadanandpai** [comment]
yes @721-atikshaikh . that works
