### ISSUE TITLE
[Challenges] Filter functionality to filter by contributor

### ISSUE THREAD

**Issue by sadanandpai** [sadanandpai/frontend-mini-challenges#386]
Filter by contributors list. Allow multi selection
![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/12962887/61fcbee4-d6fe-44a5-aacd-ec6b90e0551d)

Provide support for URL params as well

**Comment by rajnijain6** [comment]
hey, Can you assign this task to me?
