### ISSUE TITLE
[Challenges] Filter by Difficulty level

### ISSUE THREAD

**Issue by sadanandpai** [sadanandpai/frontend-mini-challenges#387]
Filter the challenges list by difficulty level. Allow multi select dropdown
![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/12962887/9d1e7e7f-544e-4c8f-ac24-254011e9f873)

**Comment by divAtGithub** [comment]
I would like to take this one. Let me know if I can work on it.

**Comment by divAtGithub** [comment]
I wasn't able to work on this issue due to some other work commitments. In the interest of getting this feature completed asap, I'm unassigning myself. Anyone else interested can take it @sadanandpai .

**Comment by harireddy7** [comment]
@sadanandpai could you assign this to me?
