### ISSUE TITLE
[Challenges] Tech stack filter

### ISSUE THREAD

**Issue by sadanandpai** [sadanandpai/frontend-mini-challenges#388]
Allow selection of tech stack using icons. Multi selection to be allowed
![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/12962887/367b9086-deed-4bbc-8f0c-cbc34ea384e1)

**Comment by Himanshu4776** [comment]
Can I work on this @sadanandpai ? Please assign it to me if no one is working on this.

**Comment by sadanandpai** [comment]
@Himanshu4776 This looks to be implemented by @sadakchap in a PR to be merged
