### ISSUE TITLE
[Leaderboard] Bug in leaderboard

### ISSUE THREAD

**Issue by sadanandpai** [sadanandpai/frontend-mini-challenges#389]
Last column breaks when person has contributions in all stack

![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/12962887/9968f88a-1c6b-41db-b7c7-e781c698f64d)

**Comment by Dev-AkshatGupta** [comment]
`Question` Is it still a issue since I have checked it with different widths and it adjusted as per requirement?
![issue](https://github.com/sadanandpai/frontend-mini-challenges/assets/53713926/8fc8f0c8-a658-47d8-ab34-28cc672a7fc7)

**Comment by sadanandpai** [comment]
Plz add first person in 1 vuejs challenge as well and check

**Comment by shubham-ram** [comment]
Hey @sadanandpai i can take this issue
