### ISSUE TITLE
[Challenges] Sort challenge list dashboard

### ISSUE THREAD

**Issue by sadanandpai** [sadanandpai/frontend-mini-challenges#390]
Provide the ability to sort the challenges (by difficulty for now)

![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/12962887/ddf1298f-37dd-4af7-871f-80ebff6d8248)

**Comment by Dev-AkshatGupta** [comment]
`Question` Are we talking about a `dropdown-select` to choose for sorting from east to difficult or difficult to easy right?

**Comment by Akshaybagai52** [comment]
@sadanandpai @Dev-AkshatGupta I'm working on this issue

**Comment by Dev-AkshatGupta** [comment]
@Akshaybagai52 Can you please get it assigned to you? It's misleading. Thanks

**Comment by Akshaybagai52** [comment]
@Dev-AkshatGupta Wait for some time @sadanandpai will assigned.
If you want to work on this issue then you can get assigned to yourself I will work on other issue

**Comment by Akshaybagai52** [comment]
Hello @sadanandpai 
Apologies for my inactivity; it's been due to work commitments.
do you have any design idea about this. it will be select dropdown right ?

**Comment by sadanandpai** [comment]
@Akhil017 is there a plan/suggestion for this

**Comment by Akhil017** [comment]
Hey @sadanandpai,
As discussed, we need to add a tabular view for the challenge. This is an example from Shadcn UI: 
https://ui.shadcn.com/examples/tasks

![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/49204264/ffa38c17-c820-49f4-87f8-db3b983b5f7e)
I am thinking along these lines.
Search box and filter dropdowns can stay the same for both table and card view.

**Comment by Akshaybagai52** [comment]
> Hey @sadanandpai, As discussed, we need to add a tabular view for the challenge. This is an example from Shadcn UI: https://ui.shadcn.com/examples/tasks
> 
> ![image](https://private-user-images.githubusercontent.com/49204264/309162667-ffa38c17-c820-49f4-87f8-db3b983b5f7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNzgzMzcsIm5iZiI6MTcwOTI3ODAzNywicGF0aCI6Ii80OTIwNDI2NC8zMDkxNjI2NjctZmZhMzhjMTctYzgyMC00OWY0LTg3ZjgtZGIzYjk4M2I1ZjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA3MjcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzOTY2NTI1NjE0MTRiOGRiODRkMjdlODM5M2M1MDQyZjcwYjgxZDA5NGIxOTcwODIzMzdiMmJlYTJhZDdiYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AacpL1Kk5ktloEUvOnjtSZsaD328kxXcv_wfBlkPlOs) I am thinking along these lines. Search box and filter dropdowns can stay the same for both table and card view.

This looks good are we making tabular view as shown in this because then sort will be on click of the td in th

**Comment by sadanandpai** [comment]
Closing the task as the impact is not much
