### ISSUE TITLE
[React] Add Memory Game as a challenge

### ISSUE THREAD

**Issue by sadanandpai** [sadanandpai/frontend-mini-challenges#392]
Add the memory game challenge which is already built here https://github.com/sadanandpai/MemoryGame to the react challenges list. Animations need not be present. Also code to be rewritten with standards & hooks

**Comment by sadakchap** [comment]
@sadanandpai Can I pick this one?

**Comment by Dev-AkshatGupta** [comment]
I will take this. Can you please assign this to me?
