### ISSUE TITLE
Add dark and light mode for the host application

### ISSUE THREAD

**Issue by sadanandpai** [sadanandpai/frontend-mini-challenges#393]
Add dark and light modes for the host application.
Each challenge lies in its respective tech stack. For now, we can focus on the host application only (home page, challenges page & leaderboard)

**Comment by Dev-AkshatGupta** [comment]
`Question` So we need to make one button on navbar to toggle between light and dark mode and only on three pages leaderboard, homepage, challenges Page, right?
If yes then please assign this task to me.
