### ISSUE TITLE
[JS] Infinite scroll is not working on bigger screen

### ISSUE THREAD

**Issue by sadanandpai** [sadanandpai/frontend-mini-challenges#397]
Infinite scroll does not work on bigger screens (height greater than loaded items)
https://sadanandpai.github.io/frontend-mini-challenges/javascript/src/challenges/infinite-scroll/
![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/12962887/76044306-f626-4662-bd1c-1b3f70bc0334)

**Comment by kumarvivekpandey** [comment]
assign this to me

**Comment by kumarvivekpandey** [comment]
![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/35356580/909e2cae-2973-4069-a163-5788c1915da1)
its working fine on bigger screen too

**Comment by sadanandpai** [comment]
I verified again. It is not working. Can you share a video if possible

**Comment by harireddy7** [comment]
It seems like for larger screens, the initial content is not scrollable. @sadanandpai can I work on this?

https://github.com/sadanandpai/frontend-mini-challenges/assets/44774504/53d6733c-4f6d-4140-b5d5-2d543b5ef021

**Comment by harireddy7** [comment]
It seems like for larger screens, the initial content is not scrollable. @kumarvivekpandey @sadanandpai Let me know if I can work on this.

https://github.com/sadanandpai/frontend-mini-challenges/assets/44774504/53d6733c-4f6d-4140-b5d5-2d543b5ef021

**Comment by sadanandpai** [comment]
@harireddy7 yes plz
