### ISSUE TITLE
[Challenge] Revamped professional UI for challenges Screen

### ISSUE THREAD

**Issue by sadanandpai** [sadanandpai/frontend-mini-challenges#398]
This is the current UI of the challenges list screen
![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/12962887/ee483224-1edb-4028-8dc9-18f4a2e60aad)

We need to come up with a revamped professional UI for challenges. This will help good UX & support future enhancements.

Plz share dummy designs and then can implementation

**Comment by sadanandpai** [comment]
this looks good

**Comment by harireddy7** [comment]
@sadanandpai 

![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/44774504/a6ae0684-f3a9-4982-996d-ba04676f9c32)

source: [dribbble](https://dribbble.com/shots/9521460-Task-Manager-Concept/attachments/1547714?mode=media)

**Comment by Akhil017** [comment]
Can we revamp the host app with Shadcn UI? I think that will make the app look more professional. @sadanandpai

**Comment by sadanandpai** [comment]
@Akhil017 sure we can

**Comment by vihangkale** [comment]
I think our main filters are JavaScript, react JS, etc. so First we should convert these filters to tabs.

**Comment by kattasahan** [comment]
Hi @sadanandpai / everyone

Just came up with some designs, Please share your thoughts..
![Frame 5 (1)](https://github.com/user-attachments/assets/ec8fb2db-8681-4bda-90bd-0d7d0df16b5a)
![Frame 10](https://github.com/user-attachments/assets/c331affe-8adc-4421-b526-9d1430bab0ba)

**Comment by sadanandpai** [comment]
This looks very attractive
