### ISSUE TITLE
Implement hamburger menu for mobile navigation

### ISSUE THREAD

**Issue by Akhil017** [sadanandpai/frontend-mini-challenges#399]
### Framework/code-stack

React

### Scope

Core application

### Description

In the current implementation, the navigation links present in the navbar are not  accessible in the mobile view. Specifically, when viewing the website on mobile devices, the navigation links become hidden , hindering user navigation and experience.

Expected Behavior:
In the mobile view, users should be able to access the navigation links conveniently, typically through a collapsible hamburger menu icon that expands to reveal the links when clicked or tapped.

### Screenshots

![navlink](https://github.com/sadanandpai/frontend-mini-challenges/assets/49204264/282dd3a2-80a4-4026-b4bd-6ae6fb7a5661)
![Screenshot 2024-02-25 105041](https://github.com/sadanandpai/frontend-mini-challenges/assets/49204264/c7e10aec-7d1a-4d83-a812-cd6d6760f8aa)

**Comment by Akhil017** [comment]
I can take up this issue @sadanandpai

**Comment by rutupatel53** [comment]
Can i also  on this issue if its not completed @sadanandpai .

**Comment by Akhil017** [comment]
Hi @rutupatel53, if you are interested, you can take on this task. I will try to take up some other issue.

**Comment by rutupatel53** [comment]
Thank you @Akhil017  .if you haven't started yet working on this issue than i want to do it if you don't mind.
