### ISSUE TITLE
[Challenges] Show no results when results are not found

### ISSUE THREAD

**Issue by sadanandpai** [sadanandpai/frontend-mini-challenges#401]
Show no results when results are not found
![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/12962887/bb32acda-6fe4-4e36-a032-8d3430a73e19)

**Comment by sadakchap** [comment]
@sadanandpai  May I take on this task?

**Comment by srujanmelam** [comment]
Is this task completed..?

**Comment by sadakchap** [comment]
@sadanandpai something like this?
![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/44117648/f09f9ec7-9f6a-407e-8969-dfa98238da45)
