### ISSUE TITLE
[Leaderboard] Make navbar with header appear proper

### ISSUE THREAD

**Issue by sadanandpai** [sadanandpai/frontend-mini-challenges#406]
Keep the UI consistent as per the standards. Move the heading to the center as shown below
![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/12962887/49f1a6b5-5e71-4f8b-bf1a-780939b9c338)

Take care of the responsive design as well

**Comment by pojith** [comment]
i can take this issues

**Comment by pojith** [comment]
can you provide path where navigation bar folder is location can you tell

**Comment by sadanandpai** [comment]
https://github.com/sadanandpai/frontend-mini-challenges/tree/main/apps/host/src/components/common/navbar

**Comment by pojith** [comment]
can u check my pr request

**Comment by Mohdsaifulla** [comment]
can you assign this to me because  i have already made correct changes.
![Screenshot from 2024-02-29 11-37-58](https://github.com/sadanandpai/frontend-mini-challenges/assets/127741371/57fe1ff1-e38f-4282-9a08-84d20ae11c75)

and its responsive as well
