### ISSUE TITLE
Setup playwright library for E2E testing

### ISSUE THREAD

**Issue by sadanandpai** [sadanandpai/frontend-mini-challenges#410]
Setup playwright library for E2E testing
https://playwright.dev/

**Comment by ranitasahaa1230** [comment]
Hi @sadanandpai , I am interested in working on this issue. Can you please assign me this?

**Comment by aman08singh** [comment]
Added a pr please check.
https://github.com/sadanandpai/frontend-mini-challenges/pull/472
