### ISSUE TITLE
[Home] Place only one CTA on home page

### ISSUE THREAD

**Issue by sadanandpai** [sadanandpai/frontend-mini-challenges#411]
Place only one CTA on home page

![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/12962887/dc8b25be-4f7e-448b-8287-85c92cc21511)

**Comment by Mohdsaifulla** [comment]
sir i wanna discuss on it  if i will remove all three button then how to get on react javascript etc route  by clicking on below icon or do we need to make another page to choose where u want  to go after clicking get started

**Comment by Mohdsaifulla** [comment]
/attempt 
i want to attempt it

**Comment by sadanandpai** [comment]
routes are present on the challeges screen
![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/12962887/06a88c57-f800-464f-b365-dba2c3f60e79)

**Comment by Mohdsaifulla** [comment]
got it  thanks
