### ISSUE TITLE
Issues with dark mode

### ISSUE THREAD

**Issue by harireddy7** [sadanandpai/frontend-mini-challenges#420]
### Framework/code-stack

React

### Scope

Core application

### Description

1. Unable to preserve dark mode between refresh
2. Select input options are not visible properly in dark mode

https://github.com/sadanandpai/frontend-mini-challenges/assets/44774504/02c191a0-f282-4605-8c61-409030ed8272

### Expected behaviour

1. Should be able to preserve dark/light modes between refresh
2. Select input options should be visible properly in both modes

### Suggested Solutions

1. Use local storage to preserve the selected mode
2. Update styles of Select options based on selected mode

**Comment by SachinMS4** [comment]
I can work on this, please assign to me.
