### ISSUE TITLE
[Host] Framer motion as animation library

### ISSUE THREAD

**Issue by sadanandpai** [sadanandpai/frontend-mini-challenges#429]
Implement framer motion animation for animations in host application. We can migrate the existing animations as well to framer

**Comment by Dev-AkshatGupta** [comment]
Please assign this to me. Thanks

**Comment by karananeja** [comment]
Can i work on this issue if its not completed @sadanandpai .

**Comment by karananeja** [comment]
Hey @Dev-AkshatGupta , have you completed the task or yet to start?

**Comment by Dev-AkshatGupta** [comment]
I have started with it @karananeja Can connect accordingly on telegram if you want to work on this one.

**Comment by karananeja** [comment]
Sure @Dev-AkshatGupta
