### ISSUE TITLE
Change the logo for dark mode

### ISSUE THREAD

**Issue by Akhil017** [sadanandpai/frontend-mini-challenges#437]
### Framework/code-stack

React

### Scope

Core application

### Description

Currently, the dark mode displays the same logo as light mode, which is unreadable. We can create a separate logo specifically designed for dark mode.

### Screenshots

![Screenshot from 2024-04-28 19-44-44](https://github.com/sadanandpai/frontend-mini-challenges/assets/49204264/6c622188-db3a-4bb5-af32-ebac5e4a602b)

**Comment by amanraina1** [comment]
Can i work on this ?
