### ISSUE TITLE
Visibility issue for multi-select options in Dark mode

### ISSUE THREAD

**Issue by Achyutem** [sadanandpai/frontend-mini-challenges#449]
### Framework/code-stack

Native (HTML, CSS, and JS)

### Scope

Core application

### Description

When we switch to Dark mode and expand the multi-select drop down, the background and the text both are light which in turn makes in unreadable.
![bug](https://github.com/sadanandpai/frontend-mini-challenges/assets/111311052/bf835d2d-3839-483d-94fe-f2719e9e94ac)

### Expected behaviour

The background should be light while the text should be darker.

### Suggested Solutions

We can simple change the text color to be dark and that would be consistent with the theming standard.

**Comment by vihangkale** [comment]
@sadanandpai I would like to take up this issue
