### ISSUE TITLE
JS: Dice Game - Replace images with HTML and CSS

### ISSUE THREAD

**Issue by sadanandpai** [sadanandpai/frontend-mini-challenges#451]
Dice Game

Dices are rendered using images. This can easily be achieved with HTML and CSS. 
Eliminate all the images.

![image](https://github.com/user-attachments/assets/960f153f-2921-42d2-b930-6904cc44e8ff)

https://sadanandpai.github.io/frontend-mini-challenges/javascript/src/challenges/dice-game/

**Comment by MadGanGithub** [comment]
I would like to work on this issue. Can you assign me?

**Comment by amanraina01** [comment]
Hey, i think i can take up this problem, could you please assign me ?
