### ISSUE TITLE
JS: Rock Paper Scissor - Add score for the game

### ISSUE THREAD

**Issue by sadanandpai** [sadanandpai/frontend-mini-challenges#452]
Add score for computer and user.
Also, add a restart button to restart the game.

![image](https://github.com/user-attachments/assets/738c2b79-827e-4ab7-a5a7-01ab9c89baac)

https://sadanandpai.github.io/frontend-mini-challenges/javascript/src/challenges/rock-paper-scissor/

**Comment by alienware96** [comment]
Hi I would like to work on this
