### ISSUE TITLE
JS: Multi Typing - Add customizations

### ISSUE THREAD

**Issue by sadanandpai** [sadanandpai/frontend-mini-challenges#453]
Provide options to users such as 
- Speed of typing
- Words to type

![image](https://github.com/user-attachments/assets/7ae4f183-bf69-4428-9f74-91efa8048757)

https://sadanandpai.github.io/frontend-mini-challenges/javascript/src/challenges/multi-typing/

**Comment by amanraina1** [comment]
@sadanandpai i would like to take up this issue
