### ISSUE TITLE
Host: Improve the visibility of tags filter in dark mode

### ISSUE THREAD

**Issue by sadanandpai** [sadanandpai/frontend-mini-challenges#468]
![image](https://github.com/user-attachments/assets/adf5517d-de6d-4931-b91a-2d47a427ac8f)

Tags filter text is not visible in dark mode

**Comment by replyre** [comment]
Hello :) @sadanandpai 
I was going through this website and saw this issue, would love to contribute to this,
please assign this to me.

**Comment by sadanandpai** [comment]
@replyre The selection is not clear. I mean which one is selected is not visible due to bad UX. can we also improve that by giving a color to the selected filter option.

**Comment by replyre** [comment]
hello @sadanandpai, I have used the theme colors to improve visibility. If you want, I can make it a lighter color.
Or if you are talking about some other filter, please share a screenshot.

**Comment by sadanandpai** [comment]
@replyre setting the selected one with blue color and text in white would be clear I feel

**Comment by replyre** [comment]
okay I will do it.
