### ISSUE TITLE
JavaScript: Weather App - Add accessibility on enter click for search

### ISSUE THREAD

**Issue by sadanandpai** [sadanandpai/frontend-mini-challenges#475]
As of now in the weather app, entering the city name and hitting the ENTER button does not work. Only a manual click-on search works. Make it accessible by allowing the ENTER press as well.

https://sadanandpai.github.io/frontend-mini-challenges/javascript/src/challenges/weather-app/

**Comment by ShadowFax1731** [comment]
I will be happy to work on this. Kindly assign.
