### ISSUE TITLE
JavaScript: Timer Quiz - Back button not working

### ISSUE THREAD

**Issue by sadanandpai** [sadanandpai/frontend-mini-challenges#476]
In the screen shown below with START button, the back button at the top left does not work as the UI overlays above it. This needs to be fixed.

![image](https://github.com/user-attachments/assets/c41ca87f-4186-48f2-9661-08a3ac8ac9ca)

https://sadanandpai.github.io/frontend-mini-challenges/javascript/src/challenges/quiz-app-with-timer/

**Comment by LSoutherton** [comment]
Hi, I would be happy to look at this for you.

**Comment by Acksout** [comment]
Made a PR fixing this issue. https://github.com/sadanandpai/frontend-mini-challenges/pull/477 @sadanandpai

**Comment by sadanandpai** [comment]
@LSoutherton, @Acksout has raised a PR. Please any other issue whenever new one becomes available
