### ISSUE TITLE
React: Stepper - Enhance the features

### ISSUE THREAD

**Issue by sadanandpai** [sadanandpai/frontend-mini-challenges#483]
https://sadanandpai.github.io/frontend-mini-challenges/react/#/stepper

Implement
- Back button functionality
- Clickable steps
- Completion component as props

**Comment by amanraina1** [comment]
I would like to work on this issue

**Comment by amanraina01** [comment]
Also, i didn't fully understand the last point in the requirements. Can you please elaborate more?

**Comment by amanraina1** [comment]
Also, i didn't understand the last point in the requirements. Can you please elaborate more?

**Comment by sadanandpai** [comment]
Ignore the 3rd point for now

**Comment by amanraina1** [comment]
@sadanandpai if any change are not upto the mark, please tell me, i will be happy to work on it again
