### ISSUE TITLE
Dropdowns should have a more descriptive placeholder text

### ISSUE THREAD

**Issue by FrozenHearth** [sadanandpai/frontend-mini-challenges#494]
### Framework/code-stack

Native (HTML, CSS, and JS) / React

### Scope

Core application

### Description

Dropdowns on the homepage don't have a descriptive enough placeholder text. It would be more user friendly if they contained a descriptive placeholder text.

If you see the screenshot, the placeholders say, "Select..." which I feel is not descriptive enough for the user to understand what the dropdown does.

### Screenshots

<img width="1646" alt="Screenshot 2024-11-04 at 12 45 37 AM" src="https://github.com/user-attachments/assets/c27a1841-eb5c-4633-8e5d-55cc78c577ff">

**Comment by myth293** [comment]
Hi! I’d like to work on this issue and have an approach in mind for solving it. Let me know if you’d like me to proceed or if there are specific guidelines I should follow.

**Comment by BaoHanNgHuynh** [comment]
Hi, I want to work this issue. Can you assign it to me
