### ISSUE TITLE
This project is awesome

### ISSUE THREAD

**Issue by Sandile-Dev01** [sadanandpai/frontend-mini-challenges#66]
I love the idea behind this project, I appreciate all the contributors but there’s a nudge of a fix you can do on the navbar in the darkmode section.

- When I make the whole page dark the navbar give a good gradient of yellow to dark but I feel like the yellow is a little bit off. As it doesn’t contrast well with the white text on the nav.😊

**Comment by sadanandpai** [comment]
@Sandile-Dev01 agree. If you have a gradient suggestion, please share. Will be happy to update

**Comment by Sandile-Dev01** [comment]
I’d reckon toggling the whole background to be dark and the Github logo to be light as well as the left-arrow. The logo of the project is transparent so I feel like it must be put inside of a container that is light as it is dark color dominated. 

And that container must be a circle.😊

**Comment by sadanandpai** [comment]
Thanks for the suggestion
