### ISSUE TITLE
Bill Split: UI and Code issue

### ISSUE THREAD

**Issue by sadanandpai** [sadanandpai/frontend-mini-challenges#67]
![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/12962887/8ee01490-e0b1-4c8d-bd88-09dd78702457)

Issues
- UI is not responsive
- UI is not clean and lacks contrast
- Code quality is poor

Request you to work on these and raise a PR

@Sukomal07

**Comment by Sukomal07** [comment]
Thank you for taking the time to review the project and providing valuable feedback. I appreciate your input and am fully committed to addressing these issues to improve the overall quality of the work.

**Comment by sadanandpai** [comment]
![image](https://github.com/sadanandpai/frontend-mini-challenges/assets/12962887/f487c17f-16b9-4012-8e1b-da615081825c)
Buttons not disabled

**Comment by Sukomal07** [comment]
is there any issue in project ?

**Comment by Sukomal07** [comment]
If everything is resolved. please close this issue.
