### ISSUE TITLE
Color generator: Usefulness

### ISSUE THREAD

**Issue by sadanandpai** [sadanandpai/frontend-mini-challenges#68]
Hi @Sukomal07 

The color generator mini app is good but is not adding much of a value at this point.
I request you to look into this [website](https://coolors.co/gradient-maker/5e3719-b2a496) and attempt to improve the app in the similar direction.

<img width="1149" alt="image" src="https://github.com/sadanandpai/frontend-mini-challenges/assets/12962887/d3ef35b1-c645-4cac-beaa-8f8021239575">

**Comment by Sukomal07** [comment]
Thank you for taking the time to review the project and providing valuable feedback. I appreciate your input and am fully committed to addressing these issues to improve the overall quality of the work.

**Comment by Sukomal07** [comment]
If everything is resolved. please close this issue.
