### ISSUE TITLE
React: Guess the number: Scope for code improvements and comments

### ISSUE THREAD

**Issue by sadanandpai** [sadanandpai/frontend-mini-challenges#74]
**Platform**: React
**Challenge**: Guess the number
**Path**: https://github.com/sadanandpai/frontend-mini-challenges/tree/main/react/src/machine-coding/guess-number

**Description**:
The coding standards and quality of the code can be improved.

- Variable names
- Code quality (functions can be refactored)
- Comments

**Comment by nayangoyal** [comment]
Hi, @sadanandpai  can you assign this issue to me? I want to work on this issue.
