### ISSUE TITLE
JavaScript: Accordion: Improvements

### ISSUE THREAD

**Issue by sadanandpai** [sadanandpai/frontend-mini-challenges#75]
Platform: JavaScript
Challenge: Accordion
Path: https://github.com/sadanandpai/frontend-mini-challenges/tree/main/native/machine-coding/accordion

Description:
Accordion functionality to be improved similar to [React Accordion](https://sadanandpai.github.io/frontend-mini-challenges/react/dist/#/accordion)

Issues:
- No "Is multiple open accordion allowed?" option
- Animation issues while opening and closing the accordion tabs

Note: UI may remain as it is

**Comment by poornima-alugubelly** [comment]
@sadanandpai can you please assign this to me? I want to work on this
