### ISSUE TITLE
[Typo] wrong headings on button

### ISSUE THREAD

**Issue by Bhanu-code** [sadanandpai/frontend-mini-challenges#95]
JS project page has "React project heading" & React projects page has "JS mini projects" heading.

![reactmini](https://github.com/sadanandpai/frontend-mini-challenges/assets/77599001/fe0f820a-a124-4de6-a85b-35e907ac6957)

![jsmini](https://github.com/sadanandpai/frontend-mini-challenges/assets/77599001/02690286-1b47-4812-9989-3dc490323ff8)

**Comment by Bhanu-code** [comment]
yes, sure!

**Comment by sadanandpai** [comment]
@krn1904 @Bhanu-code this is not an issue. Those are not headings. Those are links to navigate to challenges

**Comment by Bhanu-code** [comment]
oh, ok
